name: Build hacktv (Codeberg)

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needed: ${{ steps.check.outputs.needed }}
      sha: ${{ steps.get-sha.outputs.cid }}

    steps:
      - name: Checkout automation repo
        uses: actions/checkout@v5

      - name: Restore last built commit SHA
        uses: actions/cache/restore@v6
        with:
          path: .last_built_sha
          key: hacktv-fsphil-sha

      - name: Clone Codeberg repo
        run: git clone https://codeberg.org/fsphil/hacktv.git

      - name: Get latest commit SHA
        id: get-sha
        run: |
          CID=$(git -C hacktv rev-parse HEAD)
          echo "cid=$CID" >> "$GITHUB_OUTPUT"

      - name: Check if build is needed
        id: check
        run: |
          if [ -f .last_built_sha ] && [ "$(cat .last_built_sha)" = "${{ steps.get-sha.outputs.cid }}" ]; then
            echo "No new commit — skipping build."
            echo "needed=false" >> "$GITHUB_OUTPUT"
          else
            echo "New commit detected."
            echo "needed=true" >> "$GITHUB_OUTPUT"
          fi

  x64:
    needs: check
    if: needs.check.outputs.needed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automation repo
        uses: actions/checkout@v5

      - name: Cache APT packages
        uses: actions/cache@v6
        with:
          path: /var/cache/apt/archives
          key: apt-${{ runner.os }}
          restore-keys: |
            apt-${{ runner.os }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 zip gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
            mingw-w64-tools git make libtool cmake yasm nasm patch dpkg-dev

      - name: Clone Codeberg repo
        run: git clone https://codeberg.org/fsphil/hacktv.git

      - name: Build & package
        run: ./build_and_package_x64.sh hacktv hacktv/src/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fsphil-x64
          path: hacktv/src/dist/**

  arm64:
    needs: check
    if: needs.check.outputs.needed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout automation repo
        uses: actions/checkout@v5

      - name: Cache APT packages
        uses: actions/cache@v6
        with:
          path: /var/cache/apt/archives
          key: apt-${{ runner.os }}
          restore-keys: |
            apt-${{ runner.os }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64 zip gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 \
            mingw-w64-tools git make libtool cmake yasm nasm patch dpkg-dev

      - name: Install LLVM MinGW
        run: |
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20260224/llvm-mingw-20260224-ucrt-ubuntu-22.04-x86_64.tar.xz
          sudo mkdir -p /opt/llvm-mingw
          sudo tar -xJf llvm-mingw-20260224-ucrt-ubuntu-22.04-x86_64.tar.xz \
            --strip-components=1 -C /opt/llvm-mingw
          echo "/opt/llvm-mingw/bin" >> "$GITHUB_PATH"

      - name: Verify LLVM MinGW
        run: |
          aarch64-w64-mingw32-gcc --version
          aarch64-w64-mingw32-strip --version

      - name: Clone Codeberg repo
        run: git clone https://codeberg.org/fsphil/hacktv.git

      - name: Build & package
        run: ./build_and_package_arm64.sh hacktv hacktv/src/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: fsphil-arm64
          path: hacktv/src/dist/**

 save-sha:
   needs: [check, x64, arm64]
   if: needs.check.outputs.needed == 'true'
   runs-on: ubuntu-latest

   steps:
     - name: Checkout automation repo
       uses: actions/checkout@v5

     - name: Save latest commit SHA
       run: echo "${{ needs.check.outputs.sha }}" > .last_built_sha

     - name: Cache latest commit SHA
       uses: actions/cache/save@v6
       with:
         path: .last_built_sha
         key: hacktv-fsphil-sha
